name: Upload Python Package

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  pypi-publish:
    name: Upload release to PyPI
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/astromartini
    permissions:
      id-token: write
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel build
        pip install -r requirements.txt
        pip install .
    - name: Build
      run: |
        pyproject-build
    - name: Publish package distributions to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
